### ISSUE TITLE
Support for new addon feature - AddC3RuntimeScript and SetRuntimeModuleMainScript

### ISSUE THREAD

**Issue by MikalDev** [lostinmind-dev/lost-c3#1]
I am starting to work on porting an addon using the lost framework (nice work!)

I also want to use modules and imports, which are now supported by SDK V2, but require some different SDK calls to support them. Can this be added?

The details are here under "Using Modules"
https://www.construct.net/en/make-games/manuals/addon-sdk/guide/runtime-scripts/sdk-v2

The new main.ts file should look like:
```javascript
import "./plugin.js";
import "./type.js";
import "./instance.js";
import "./conditions.js";
import "./actions.js";
import "./expressions.js";
```

Also add in the editor plugin:
```javascript
 this._info.SetRuntimeModuleMainScript("c3runtime/main.js")
```

For the module files add:
```javascript
this._info.AddC3RuntimeScript("c3runtime/mymodule.js");
```

**Comment by dakln** [comment]
https://github.com/lostinmind-dev/lost-c3/releases/tag/1.2.4
