### ISSUE TITLE
Is it possible to add code to c3runtime/types.js

### ISSUE THREAD

**Issue by MikalDev** [lostinmind-dev/lost-c3#3]
In SDKV1, I am adding a 'central' object to the type which I can use from each object instance, howwould I add similar code in this frame work (I tried modifying the files under _base in my addon project dir, but I think it is being pulled from the jsr library path instead.)

**Comment by dakln** [comment]
https://github.com/lostinmind-dev/lost-c3/releases/tag/1.2.4
